# Google Cloud Run deployment with Datadog sidecar

steps:
  - name: 'docker/compose'
    args: ['-p', '${_SERVICE_NAME}', 'build', '--no-cache']
    env:
    - 'DD_API_KEY=${_DD_API_KEY}'
    - 'DD_ENV=${_DD_ENV}'
    id: BUILD_GCR_DEMO
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    env:
      - "APP_NAME=${_APP_NAME}"
      - "IMAGE_APP=${_IMAGE_APP}"
    script: |
      docker tag ${APP_NAME} ${IMAGE_APP}
    id: TAG_GCR_DEMO_API
    waitFor:
      - BUILD_GCR_DEMO

  # - name: "gcr.io/cloud-builders/docker"
  #   env:
  #     - "COLLECTOR_NAME=${_COLLECTOR_NAME}"
  #     - "IMAGE_COLLECTOR=${_IMAGE_COLLECTOR}"
  #   script: |
  #     docker tag ${COLLECTOR_NAME} ${IMAGE_COLLECTOR}
  #   id: TAG_GCR_DEMO_DD_AGENT
  #   waitFor:
  #     - BUILD_GCR_DEMO

  - name: "gcr.io/cloud-builders/docker"
    env:
      - "IMAGE_APP=${_IMAGE_APP}"
    script: |
      docker push ${IMAGE_APP}
    id: PUSH_GCR_DEMO_API
    waitFor:
      - TAG_GCR_DEMO_API

  # - name: "gcr.io/cloud-builders/docker"
  #   env:
  #     - "IMAGE_COLLECTOR=${_IMAGE_COLLECTOR}"
  #   script: |
  #     docker push ${IMAGE_COLLECTOR}
  #   id: PUSH_GCR_DEMO_DD_AGENT
  #   waitFor:
  #     -  TAG_GCR_DEMO_DD_AGENT

  - name: "ubuntu"
    env:
      - "SERVICE_NAME=${_SERVICE_NAME}"
      - "IMAGE_APP=${_IMAGE_APP}"
      - "IMAGE_COLLECTOR=${_IMAGE_COLLECTOR}"
    script: |
      sed -i s@%SERVICE_NAME%@${SERVICE_NAME}@g run-service.yaml
      sed -i s@%DD_AGENT_IMAGE%@${IMAGE_COLLECTOR}@g run-service.yaml
      sed -i s@%SAMPLE_APP_IMAGE%@${IMAGE_APP}@g run-service.yaml
    id: REPLACE_YAML_VALUE
    waitFor: ["-"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    env:
      - "REGION=${_REGION}"
    script: |
      gcloud run services replace run-service.yaml --region ${REGION} --quiet
    id: DEPLOY_MULTICONTAINER
    waitFor:
      - PUSH_GCR_DEMO_API
      # - PUSH_GCR_DEMO_DD_AGENT
      - REPLACE_YAML_VALUE

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    env:
      - "REGION=${_REGION}"
      - "SERVICE_NAME=${_SERVICE_NAME}"
    script: |
      gcloud run services set-iam-policy ${SERVICE_NAME} policy.yaml --region ${REGION} --quiet
    id: ALLOW_UNAUTHENTICATED
    waitFor:
      - DEPLOY_MULTICONTAINER

substitutions:
  _SERVICE_NAME: gcr-demo
  _REGION: us-central1
  _REGISTRY: ${_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_SERVICE_NAME}
  _APP_NAME: ${_SERVICE_NAME}_api
  _COLLECTOR_NAME: ${_SERVICE_NAME}_dd-agent
  _IMAGE_APP: ${_REGISTRY}/${_APP_NAME}
  _IMAGE_COLLECTOR: ${_REGISTRY}/${_COLLECTOR_NAME}
  # _SA_NAME: gcr-demo-sa

images:
  - ${_IMAGE_APP}
  # - ${_IMAGE_COLLECTOR}

# comment out the following line if you want to run Cloud Build with the existing
# service account with the following roles.
# * roles/iam.serviceAccountUser
# * roles/storage.objectViewer
# * roles/logging.logWriter
# * roles/artifactregistry.createOnPushWriter
# * roles/run.admin
# serviceAccount: "projects/${_GCP_PROJECT_ID}/serviceAccounts/${_SA_NAME}@${_GCP_PROJECT_ID}.iam.gserviceaccount.com"

options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY