apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: ALPHA
  name: "%SERVICE_NAME%"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen1
      #   run.googleapis.com/container-dependencies: '{"app":["collector"]}'
    spec:
      containers:
        - image: "%SAMPLE_APP_IMAGE%"
          name: app
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /
              port: 3000
      #     volumeMounts:
      #       - mountPath: /logging
      #         name: shared-logs
      #   - image: "%DD_AGENT_IMAGE%"
      #     name: collector
      #     env:
      #       - name: DD_HEALTH_PORT
      #         value: "5555"
      #     resources:
      #       requests:
      #         memory: "256Mi"
      #         cpu: "200m"
      #       limits:
      #         memory: "256Mi"
      #         cpu: "200m"
      #     volumeMounts:
      #       - name: dockersocket
      #         mountPath: /var/run/docker.sock
      #     startupProbe:
      #       httpGet:
      #         path: /health
      #         port: 5555
      #       initialDelaySeconds: 15
      #       periodSeconds: 15
      #       timeoutSeconds: 5
      #       successThreshold: 1
      #       failureThreshold: 3
      # volumes:
      #   - name: shared-logs
      #     emptyDir:
      #       medium: Memory
      #       sizeLimit: 512Mi
      #   volumes:
      #     - hostPath:
      #         path: /var/run/docker.sock
      #       name: dockersocket